services:
  laravel-docker:
    container_name: bibliotecaonline
    build: .
    volumes:
      - /:/var/www/html
    ports:
      - "8000:8000"
      - "8099:80"

  pgsql:
    image: postgres:13.12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bibliotecaonline
    ports:
      - "5499:5432"
